version: '3'

services:
  react_app:
    image: ryan212/react_chat:latest
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
