version: '3'

services:
  dev:
    image: ryan212/react_chat:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app 
      - /app/node_modules
    user : Dev_User
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
