name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-build
        

      # - name: Deploy & Production
      #   run: |
      #     npm run deploy
